#!/bin/sh

if test "$#" != 1; then
    echo "`basename $0` /path/to/clone"
    exit 1
fi

which gitdm 2>&1 >/dev/null
if test "$?" != "0"; then
    echo "gitdm isn't in the PATH, please fix it before rerunning"
    exit 1
fi

exec_dir=`pwd`
scripts_dir=$exec_dir/`dirname $0`
cd $1


if test -e $exec_dir/all-lo.log; then
    rm $exec_dir/all-lo.log
fi

$scripts_dir/merge-log >$exec_dir/all-lo.log

cd $exec_dir
cat all-lo.log | gitdm -u -D >/dev/null
cat all-lo.log | gitdm -u -x git-data.csv -o git-reports.txt

#Convert the date statistics to some useful CSV
cat datelc | sed -e 's/\ \+/,/g' >datelc.csv
rm datelc
